### ISSUE TITLE
установка с ключом save

### ISSUE THREAD

**Issue by Scicommunity** [rpiontik/archivist#1]
По результатам тестирования в ВАРМ, опция save добавляет в конец секции imports подключение методологических пакетов. Однако без опции такая же запись создается в начале секции. По факту save ни на что не влияет.
на скриншоте слева - без save, справа - с save
![20240222_193539](https://github.com/rpiontik/archpkg/assets/140635737/4792c3d3-5285-4159-b71a-e82d31f964c7)

**Comment by rpiontik** [comment]
Проблема остается?
